### ISSUE TITLE
Tweak wishlist icon

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [themebeez/orchid-store#120]
Reported by Jason

Hello,

I think I've found a bug. When I hover over a product an empty heart
appears, if I click the empty heart the item gets added to my wish list.
The problem is that it doesn't turn solid white indicating it's been
added to my wish list. If I then reload the page the heart becomes solid
white because the item is on my wish list. I think it should turn solid
white as soon as I click the heart. Not a huge deal but maybe something
that could be fixed in the next update.

Thanks,
Jason

**Comment by umparu** [comment]
On the mobile does not hold the size - decreases. When you do a reduction with the touch of your fingers.

**Comment by h1dd3nsn1p3r** [comment]
Hello @umparu can you please share some screenshot?

**Comment by umparu** [comment]
Sorry. Found a reason
But I found another mistake.
The contents of the basket in the menu does not appear on regular WordPress pages
https://butifut.ru/gol-bonus/

**Comment by h1dd3nsn1p3r** [comment]
Fixed in version 1.1.5

**Comment by umparu** [comment]
doesn't work anyway - updated to 1.1.5
