### ISSUE TITLE
In french, the default text in search bar need a space

### ISSUE THREAD

**Issue by jaigoff** [themebeez/orchid-store#142]
In the default text, in the header search, we have "Rechercherdes produits..." the good way to write it is "Rechercher des produits..."

**Comment by h1dd3nsn1p3r** [comment]
Dear @jaigoff, Thank you. We will ask the French translator to fix that shortly.

**Comment by h1dd3nsn1p3r** [comment]
@jaigoff, French PTE has already been notified to fix that here https://translate.wordpress.org/projects/wp-themes/orchid-store/fr/default/?page=23.

**Comment by h1dd3nsn1p3r** [comment]
Dear @jaigoff, French PTE have fixed that typo error. You will get translation update in your WP shortly. 
Thanks 👍

**Comment by jaigoff** [comment]
> Dear @jaigoff, French PTE have fixed that typo error. You will get translation update in your WP shortly.
> Thanks 👍

Thanks the team for your reactivity!
