### ISSUE TITLE
Tab widget has an issue

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [themebeez/orchid-store#153]
Tab widget has an issue when it is used multiple times. [jQuery]

**Comment by h1dd3nsn1p3r** [comment]
@Asok17 Once the **PRODUCT CATEGORY FILTER** widget is used repeatedly also the ID is repeated. Got to fix this

**Comment by Asok17** [comment]
Parent wrapper of current clicked tab is searched and tab functionality is initiated only for the selected tab widget.
