### ISSUE TITLE
Out of stock product information in product catalog 

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [themebeez/orchid-store#160]
Please add markup as follows:

<div class="product-thumb-wrap">
       <span class="stock-info">Out of Stock</span>
</div>

Reference Link: https://demo.themebeez.com/demos-2/orchid-store/product/led-smart-television/

**Comment by Asok17** [comment]
Option added and applied effectively. Styling is left to be done.

**Comment by h1dd3nsn1p3r** [comment]
Done https://github.com/themebeez/orchid-store/commit/eb9d40abe30fe03caaa53b83e2e28c3501cb9d6b
