### ISSUE TITLE
Buttons “+” and “-” near “Add to cart” disappear

### ISSUE THREAD

**Issue by newmanclimb** [themebeez/orchid-store#206]
I encountered problem, when using Orchid Store Theme with YITH WooCommerce Product Bundles plugin.

When I use simple product – everything is like it should be:

https://ibb.co/S5Lrpg4

But when I’m using the bundle product, buttons “+” and “-” near “Add to cart” disappear:

https://ibb.co/SQ1qbDL

The page I need help with: https://u97026.test-handyhost.ru/product/stellazh-napolnyj-uzkij/

**Comment by h1dd3nsn1p3r** [comment]
Fixed in version 1.2.9
