### ISSUE TITLE
Search module not shown on desktop if WooCommerce is disabled

### ISSUE THREAD

**Issue by AlceoMazza** [themebeez/orchid-store#252]
After a recent update the search module in the header is not being shown anymore if WooCommerce is disabled.

**Comment by h1dd3nsn1p3r** [comment]
Hi @AlceoMazza,

Nice find. I agree with you. Default search should still work when WooCommmerce is not active.

![image](https://user-images.githubusercontent.com/21140404/188074205-baa540a0-381e-4199-bd6e-cf279376358c.png)

We will fix this BUG upcoming week. 

Thank you
