### ISSUE TITLE
Fix deprecated Function get_page_by_title

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [themebeez/orchid-store#280]
![image](https://user-images.githubusercontent.com/21140404/229432705-b2a66e69-111f-43a9-977e-f5dbc9216032.png)

**Comment by Asok17** [comment]
How did you get this error?? @h1dd3nsn1p3r

**Comment by h1dd3nsn1p3r** [comment]
Update: The issue was caused due to Addonify wishlist.
